name: pipen_echo
description: Wrapper for Laravel Echo
version: 1.0.0
homepage: "https://github.com/juanfelipepipen/pipen-echo"
repository: "https://github.com/juanfelipepipen/pipen-echo"

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dart_pusher_channels: ^1.2.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
